fastlane_version "2.28.3"

platform :ios do
    before_all do
        cocoapods(podfile: './ios/Podfile')
    end

    desc "Build a new ios version"
    lane :build do
        match(type: 'development', git_basic_authorization: Base64.strict_encode64("bouthouri:b3c521a61ebb2da3c26f3f07d1eed96fe5703b78"))
        gym(scheme: 'coockies', workspace: './ios/coockies.xcworkspace')
        firebase_app_distribution(
            app: "1:533425593106:ios:29eed1ed1ff8b0f72071cb",
            testers: "oussamabo@xtech.guru, oussama@bouthouri.com"
        )
    end


  after_all do |lane|
  end

  error do |lane, exception|
  end
end

platform :android do

    desc "Build a new android version"
    lane :build do
        gradle(task: 'clean', project_dir: 'android/')
        gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
        firebase_app_distribution(
            app: "1:533425593106:android:2b04a636c4575c9e2071cb",
            testers: "oussamabo@xtech.guru, oussama@bouthouri.com"
        )
    end


  after_all do |lane|
  end

  error do |lane, exception|
  end
end