fastlane_version "2.28.3"

platform :ios do
    before_all do
        cocoapods(podfile: './ios/Podfile')
    end

    desc "Build a new ios version"
    lane :build do
        if ENV['CI']
            create_keychain(
                name: "keychain",
                password: "123456",
                default_keychain: true,
                unlock: true,
                timeout: 3600,
                lock_when_sleeps: false
            )
            match(
                keychain_name: "keychain",
                keychain_password: "123456",
                type: 'development'
                readonly: is_ci
            )
            gym(scheme: 'coockies', workspace: './ios/coockies.xcworkspace')
            firebase_app_distribution(
                app: "1:533425593106:ios:29eed1ed1ff8b0f72071cb",
                testers: "oussamabo@xtech.guru, oussama@bouthouri.com"
            )
        else
            match(type: 'development')
            gym(scheme: 'coockies', workspace: './ios/coockies.xcworkspace')
            firebase_app_distribution(
                app: "1:533425593106:ios:29eed1ed1ff8b0f72071cb",
                testers: "oussamabo@xtech.guru, oussama@bouthouri.com"
            )
        end
    end


  after_all do |lane|
  end

  error do |lane, exception|
  end
end

platform :android do

    desc "Build a new android version"
    lane :build do
        gradle(task: 'clean', project_dir: 'android/')
        gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
        firebase_app_distribution(
            app: "1:533425593106:android:2b04a636c4575c9e2071cb",
            testers: "oussamabo@xtech.guru, oussama@bouthouri.com"
        )
    end


  after_all do |lane|
  end

  error do |lane, exception|
  end
end