name: Ruby Gem

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build + Publish
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - run: bundler --version
    - name: install firebase cli
      run: curl -sL https://firebase.tools | bash
    - run: bundle exec fastlane ios build
    - run: bundle exec fastlane android build
