name: Ruby Gem

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build + Publish
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        
    - run: bundle install
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

      
    - name: install firebase cli
      run: curl -sL https://firebase.tools | bash
      
    - name: Setup NodeJs
      uses: actions/setup-node@v1
      with:
        node-version: '10.16.3'

    - uses: c-hive/gha-yarn-cache@v1
    - run: yarn install
      
    - name: Run fastlane firebase_beta
      env:
        MATCH_GIT_BASIC_AUTHORIZATION: 'b3c521a61ebb2da3c26f3f07d1eed96fe5703b78'
      run: |
        bundle exec fastlane ios build
        bundle exec fastlane android build
